---
title: "Bibliography"
output: html_document
---


\

### <b>Peer-reviewed Research</b> 

[Simon, A. D. F., Marx, H. E., and Starzomski, B. M. (2021) Phylogenetic restriction of plant invasion in drought-stressed environments: implications for insect‐pollinated plant communities in water‐limited ecosystems. Ecology and evolution. 11: 10042-10053]("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8328464/")

[Simon A. D. F., Adamczyk E. M., Basman A., Chu J. W. F., Gartner H. N., Fletcher K., Gibbs C. J., Gibbs D. M., Gilmore S. R., Harbo R. M., Harris L. H., Humphrey E., Lamb A., Lambert P., McDaniel N., Scott J., and Starzomski B. M. (2022) Toward an atlas of Salish Sea biodiversity: the flora and fauna of Galiano Island, British Columbia, Canada. Part I. Marine zoology. Biodiversity Data Journal. 10: e76050](https://bdj.pensoft.net/article/76050/")

[Simon, A. D. F., Best, L. R., and Starzomski, B. M. (in press) Evidence of bumble bee species extirpation and colonization: Galiano Island, British Columbia, Canada. Northwest Science.](https://biogaliano.org/galiano-island-harnesses-inaturalist-to-detect-historical-changes-in-the-local-bumble-bee-community/)

\

### <b>Presentations</b>

Simon, A. D. F. (2018) The bumble bees of Galiano Island, BC. Entomological Society of America (oral presentation of preliminary findings from MSc research during international conference proceedings).

Simon, A. D. F. (2019) Backyard biodiversity: a model for community-based biodiversity research. Valdes Island Conservancy AGM (oral presentation of independent research).

Simon, A. D. F. (2019) Implications of seasonal drought for plant-pollinator communities in the southern Gulf Islands. BC Protected Areas Research Forum (oral presentation of preliminary findings from MSc research during provincial conference proceedings).

Simon, A. D. F. (2022) Bumble bees in the Southern Gulf Islands. Mayne Island Conservancy (oral presentation of outcomes of MSc research).

Simon, A. D. F. (2022) The Life and Legacy of Harvey Janszen. Victoria Natural History Society (oral presentation of independent research).

Simon, A. D. F. (2022) Toward an atlas of Salish Sea Biodiversity. Wonders of the Salish Sea (oral presentation of independent research).

Simon, A. D. F., and Basman, A. (2022) Biodiversity beyond boundaries: building capacity for pluralistic biodiversity research. Salish Sea Ecosystem Conference (oral presentation of independent research during international conference proceedings).

\

### <b>In the Media</b> 

Simon, A. D. F. (2017, September 21) Citizen science platform iNaturalist is testing artificial intelligence to help with species identification. Canadian Geographic [https://canadiangeographic.ca/articles/citizen-science-platform-inaturalist-is-testing-artificial-intelligence-to-help-with-species-identification/](https://canadiangeographic.ca/articles/citizen-science-platform-inaturalist-is-testing-artificial-intelligence-to-help-with-species-identification/)

Simon, A. D. F. (2022, June 28) A Community’s Quest to Document Every Species on Their Island Home. Hakai Magazine [https://hakaimagazine.com/features/a-communitys-quest-to-document-every-species-on-their-island-home](https://hakaimagazine.com/features/a-communitys-quest-to-document-every-species-on-their-island-home/)

\

### <b>Theses</b>

Simon, A. D. F. (2016) Potential risks and mitigations of prescribed fire in caribou habitat (Honour's Thesis).

[Simon, A. D. F. (2020) Water into nectar: the effects of seasonal drought on bumble bee and flowering plant communities (MSc thesis).](https://dspace.library.uvic.ca:8443/handle/1828/11837/)

