---
title: "Bibliography"
output: html_document
---


\

### <b>Peer-reviewed Research</b> 

[Simon, A.D.F., Basman, A., Martin, R.A., Robinson, C., & Cronk, Q. (2025). Detecting extirpation: A localized approach to a global problem. Plants, People, Planet.](https://doi.org/10.1002/ppp3.70130)

[Gonzalez, A., O’Connor, M.I., Bates, A.E., van Dam-Bates, P., Bobiwash, K., Burton, C., Eckert, I., Dominique, G.C., Idrobo, J., Pollock, L.J., Simon, A.D.F., Slein, M., Sólymos, P., Starzomski, B.M., Sunday, J.M., & Tekwa, E.W. (2025). A Biodiversity Observation Network to support conservation action and mainstream knowledge in Canada. Facets, 10, 1-19.](https://doi.org/10.1139/facets-2024-0206)

[McMullin, R., Simon, A.D.F., Brodo, I., Wickham, S., Bell-Doyon, P., Kuzmina, M., & Starzomski, B.M. (2024) DNA barcoding aids in generating a preliminary checklist of the lichens and allied fungi of Calvert Island, British Columbia: Results from the 2018 Hakai Terrestrial BioBlitz. Biodiversity Data Journal. 12:e120292](https://doi.org/10.3897/BDJ.12.e120292)

[Simon, A.D.F., Best, L.R., & Starzomski, B.M. (2023) Evidence of bumble bee extirpation and colonization: Galiano Island, British Columbia, Canada. Northwest Science. 96(3-4):206-219](https://doi.org/10.3955/046.096.0305)

[Simon, A.D.F., Adamczyk, E.M., Basman, A., Chu, J.W.F., Gartner, H.N., Fletcher, K., Gibbs, C.J., Gibbs, D.M., Gilmore, S.R., Harbo, R.M., Harris, L.H., Humphrey, E., Lamb, A., Lambert, P., McDaniel, N., Scott, J., & Starzomski, B.M. (2022) Toward an atlas of Salish Sea biodiversity: the flora and fauna of Galiano Island, British Columbia, Canada. Part I. Marine zoology. Biodiversity Data Journal. 10: e76050](https://doi.org/10.3897/BDJ.10.e76050)

[Simon, A.D.F., Marx, H.E., & Starzomski, B.M. (2021) Phylogenetic restriction of plant invasion in drought-stressed environments: implications for insect‐pollinated plant communities in water‐limited ecosystems. Ecology and evolution. 11(15): 10042-10053](https://doi.org/10.1002/ece3.7776)

\

### <b>In Preparation</b>

Webber, M., van Asselt, A., Basman, A., Chang, A., Humphrey, E., Lemay, M., Morien, E., & Simon, A.D.F. (In Prep.) An annotated checklist of the diatoms (Bacillariophyceae) of the Salish Sea, Cold Temperate Northeast Pacific.

\

### <b>Presentations, Workshops</b>

Simon, A.D.F., Basman, A. (2024) Frameworks for community engagement in long-term ecological research. Biodiversity Beyond Boundaries: mobilizing data for the future of our shared waters.

Cronk Q., Simon, A.D.F., Martin, R.M. (2024) Operationalizing the study of local extirpation: the key role of herbaria. Botany 2024.

Simon A.D.F., Best, L.R., Starzomski, B.M. (2024) Community science and systematic sampling provide convergent evidence for historical change in an island bumble bee community. Canadian Society for Ecology and Evolution.

Simon A.D.F. (2024) Using historical and community science data to detect change in bumble bee and vascular plant communities on Galiano Island. Community Science Webinar, Coastal Douglas-fir Conservation Partnership.

Andy, K., & Simon A.D.F. (2024) The use of community science to develop integrated species distribution models. Community Science Webinar, Coastal Douglas-fir Conservation Partnership.

Hessing-Lewis, M., Beaty, F., Collins, K., Paroo, E., Simon, A.D.F., Van Der Stap, T. (2024) Biodiversity data mobilization in British Columbia and Washington waters. Northeast Pacific Coastal Biodiversity Action Network.

Srivastava, D.S., Menchions, E., Lavender, T. M., & Simon A.D.F. (2023) Data Rescue Project: Janszen Legacy Project hack-a-thon. Canadian Institute for Ecology and Evolution, Living Data Project.

Aitken, J., Ayotte, D., Basman, A., Carpendale, H., D'Souza, M., Georgeson, J., Simon, A.D.F., & Wilson, L. (2023) Transboundary Gathering: Digital ecocultural mapping in the Salish Sea. Whiteswan Environmental, Institute for Multidisciplinary Ecological Research in the Salish Sea, Inclusive Design Research Centre.

Gonzalez, A., O'Connor, M.I., Bates, A.E., Bobiwash, K., van Dam-Bates, P., Eckert, I., Gravel, D., Idrobo, J., Pollock, L.J., Sólymos, P., Simon, A.D.F., Slein, M., Starzomski, B.M., Sunday, J.M., Tekwa, E.W. (2023) Canadian Biodiversity Observation Network working group, Canadian Institute for Ecology and Evolution.

Simon, A.D.F., & Basman, A. (2023) Co-creating a biodiversity assessment framework. Howe Sound Conservation Network Gathering, Howe Sound Biosphere Region Initiative.

Simon, A.D.F., & Basman, A. (2022) Biodiversity beyond boundaries: building capacity for pluralistic biodiversity research. Salish Sea Ecosystem Conference.

Simon, A.D.F., Gibbs D.M., & Lamb, A. (2022) Toward an atlas of Salish Sea Biodiversity. Wonders of the Salish Sea.

Simon, A.D.F., & Janszen, P. (2022) The life and legacy of Harvey Janszen. Victoria Natural History Society. (also presented for Friends of Ecological Reserves AGM)

Simon, A.D.F. (2022) Bumble bees in the Southern Gulf Islands. Mayne Island Conservancy.

Simon, A.D.F. (2021) Salish Sea Symposium. Friday Harbour Labs, University of Washington.

Sandilands, C., Magner, L.D., & Simon, A.D.F. (2020) Storying climate change in the Salish Sea. Huxley College of the Environment, Western Washington University, Salish Sea Institute.

Simon, A.D.F. (2019) Backyard biodiversity: a model for community-based biodiversity research. Valdes Island Conservancy AGM.

Simon, A.D.F. (2019) Eight ways YOU can contribute to biodiversity research and conservation. Galiano Library.

Simon, A.D.F. (2019) Implications of seasonal drought for plant-pollinator communities in the southern Gulf Islands. BC Protected Areas Research Forum.

Simon, A.D.F. (2018) The bumble bees of Galiano Island, BC. Entomological Society of America.

\

### <b>In the Media</b> 

Doll, S. (2023, August 5) [Maxwell Creek Watershed Project Field Files Part 2: Developing surveying methodologies](https://www.raincoast.org/2022/08/maxwell-creek-watershed-project-field-files-part-2-developing-surveying-methodologies/). Raincoast Conservation Foundation.

Wang, M. (2022, June 28) [A Community’s Quest to Document Every Species on Their Island Home](https://hakaimagazine.com/features/a-communitys-quest-to-document-every-species-on-their-island-home) Hakai Magazine.

Wood, D. (2020, Summer) Stumbling toward oblivion: without provincial legislation, British Columbia's endangered species face extinction. British Columbia Magazine, 62(2), 32-33.

Wang, M. (2017, September 21) [Citizen science platform iNaturalist is testing artificial intelligence to help with species identification](https://canadiangeographic.ca/articles/citizen-science-platform-inaturalist-is-testing-artificial-intelligence-to-help-with-species-identification/). Canadian Geographic.

\

### <b>Other Works</b>

Magner, L., & Simon, A.D.F. (2019) Key to the Conifers of Galiano Island, BC, 2150. In C. Sandilands (Ed.), Rising Tides (pp. 199–204). Halfmoon Bay, BC: Caitlin Press.

\

### <b>Theses</b>

[Simon, A.D.F. (2020) Water into nectar: the effects of seasonal drought on bumble bee and flowering plant communities (MSc thesis).](https://dspace.library.uvic.ca:8443/handle/1828/11837/)

Simon, A.D.F. (2016) Potential risks and mitigations of prescribed fire in caribou habitat (Honour's Thesis).
