---
title: "Curriculum Vitae"
output: html_document
---
\

<div style="text-align: right"><h1>Andrew Simon</h1></div>
<div style="text-align: right">Biodiversity Research Centre | Department of Zoology \ </div>
<div style="text-align: right">University of British Columbia \ </div>
<div style="text-align: right">Vancouver, BC, Canada V6T 1Z4 \ </div>
<div style="text-align: right">adfsimon@zoology.ubc.ca \ </div>
<div style="text-align: right">[add personal website url] </div>
\
\

### Education 
|                    |                        |
|:-------------------|:-----------------------|
|**Sept 2022 to present**|**PhD Student - Zoology**|
||University of British Columbia - Vancouver, British Columbia|
||
|**2020**|**Master of Science - Environmental Studies** |
||University of Victoria - Victoria, British Columbia|
||
|**2016**|**Bachelor of Arts and Sciences**|
||Quest University Canada - Squamish, British Columbia|
||

### Work Experience
|                    |                        |
|:-------------------|:-----------------------|
|**Nov 2022 to present**|**Biodiversity Specialist - Átl’ka7tsem/Howe Sound Biosphere Region Initiative**|
||Átl’ka7tsem/Howe Sound Biosphere Reserve, British Columbia|
|» Co-design integrative biodiversity assessment framework synthesizing comprehensive biodiversity and remote sensing datasets||
|» Collaborate with diverse stakeholders to achieve harmonized solutions for data management, meeting needs of diverse knowledge communities, in support of biodiversity research and conservation||
|**Sept 2022 to present**|**Research Assistant - UBC O'Connor Lab / Advisian**|
||Iqaluit / Pond Inlet, Nunavut|
|» Quantify biomass and carbon sequestration in Arctic kelp communities|
|» Determine community composition using morphological and molecular techniques|
|» Apply deep learning to estimate spatial extent of nearshore macroalgae|
|» Develop models to scale up estimates of standing biomass and carbon from local to regional scales|
|
|**Sept 2022 to present**|**Research Assistant – UBC O'Connor Lab / Hakai Institute**|
||Vancouver, British Columbia|
|» Coordinate UN Decade on Ocean Conservation Biodiversity Synthesis Hub|
|» Identify science and policy gaps to overcome under the banner of the UN Decade on Ocean Conservation|
|» Create digitial resources supporting transboundary collaboration in Salish Sea Marine Science and Conservation|
|



##### Contractor – BC Conservation Data Centre (Sept 2021 to present)
Southern Gulf Islands, British Columbia \
» Conduct floristic inventories and rare species surveys focusing on rare lichens, bryophytes, and vascular plants
\
» Map species of conservation concern using NatureServe Biotics5
\
» Monitor rare vascular plant populations, e.g., Plagiobothrys tenellus
\

##### Biodiversity Specialist – Keefer Ecological Services Ltd. (Nov 2020 to Aug 2022)
Galiano Island / Cranbrook, British Columbia \
» Conducted rare species inventories and terrestrial ecosystem mapping 
\
» Developed habitat suitability index and connectivity models for rare and vulnerable species, inc. mountain caribou
\
» Developed project proposals and budgets, and coordinate complex multidisciplinary projects in a team environment
\

##### Stewardship Coordinator - Mayne Island Conservancy (Jan 2019 to Aug 2019)
Mayne Island, British Columbia \
» Coordinated inter-island bioblitz focusing on Galiano and Mayne Islands
\
» Compiled comprehensive dataset of historical baseline and contemporary species occurrence data using R and iNaturalist
\
» Prepared conservation management plans & implemented restoration projects focusing on private & protected lands
\

##### Independent Environmental Consultant (2015 to 2020)
Galiano Island, British Columbia \
» Implemented geospatial infrastructure for BC Parks Biodiversity Mapping
Project, inc. >1,000 protected areas
\
» Completed forest cover maps, inventories & management plans covering over 600 ha in the Coastal Douglas-fir (CDF) Biogeoclimatic Zone
\
» Clients inc.: BC Parks, the Galiano Club, Galiano Conservancy Association, BC Ministry of the Environment, & Keefer Ecological Services Ltd.
\

##### Researcher – Parks Canada (2016)
Mt. Revelstoke / Glacier / Banff / Jasper National Parks, British Columbia \
» Synthesized technical reports on the potential risks and mitigations of prescribed fire in caribou habitat in collaboration with experts & Parks Canada officials
\

##### Research and Field Assistant – Enlichened Consulting Ltd. (2015 to 2018)
Clearwater / Robson Valley / Tumbler Ridge / Vancouver Island, British Columbia \
» Assisted in ecological research, biodiversity inventories & rare plant surveys throughout BC, focusing on lichens, bryophytes, & vascular plants
\
» Collected field data, maintained databases, curated UBC lichen herbarium
\
\

### Awards and Certifications
##### Occupational First Aid (2022)
##### sRPAS Basic License Transport Canada (2021)
##### Royal BC Museum Volunteer Award (2020)
##### Islands Trust Community Stewardship Award (2019)
##### Wetland Keepers Certificate (2015)
\

### Leadership
##### <a href="https://imerss.org/">Institute for Multidisciplinary Ecological Research in the Salish Sea (2020-2022)</a>
President and founding director \

##### Capital Regional District Galiano Island Parks and Recreation Commission (2019—2022)
Commissioner \

##### <a href="https://biogaliano.org/">Biodiversity Galiano Island Project (2016—2022)</a>
Project curator \
\
\

### Mentorship
