---
title: CV
name: Andrew
surname: Simon
position: "PhD Student | Zoology | University of British Columbia"
address: "281 Highland Road, Galiano Island, BC, Canada, V0N 1P0"
phone: (250) 888-6144
www: imerss.org
email: "adfsimon@zoology.ubc.ca"
#twitter: mariecurie
#github: mariecurie
#linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Ecologist and aspiring data scientist"
output: 
  vitae::markdowncv:
    theme: kjhealy
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(gsheet)
library(RefManageR)
library(tidyverse)
library(vitae)
```

## Education

```{r education}

gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1nS5Lz1oQUSNLmF-RXKzcNAE_piFYgA0vp_iKF5LtRLE/edit?usp=sharing", sheet="Education") %>%
  vitae::detailed_entries(what = Degree,
                          when = Year,
                          where = Institution, 
                          with = Location)
```

## Work History

```{r}

gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1V7-aia0Y570R5dJ9iTQdEQZ46J-4isaHOzo83mpl1HA/edit?usp=sharing", sheet="Work") %>%
  vitae::detailed_entries(what = Job,
                          when = Year,
                          where = Organization, 
                          with = Location,
                          why = Details)

```

## Leadership

```{r}

gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1BUsrwXlt7WECMqla4BlSwk58_lVHXx1n50sylvCrM1Q/edit?usp=sharing", sheet="Leadership") %>%
  vitae::detailed_entries(what = Role,
                          when = Year,
                          where = Organization, 
                          with = Location,
                          why = Details)

```

## Awards

```{r}

gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1cRU0-a9tYSgKipazUV_FHOPgqiqhK8ikZ_OFB1CE3vU/edit?usp=sharing", sheet="Awards") %>%
  vitae::detailed_entries(what = Organization,
                          when = Year,
                          where = Award, 
                          with = Location,
                          why = Details)

```

## Certifications

```{r}

gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1rv1EJuD3hzt2SzbeSOUkmiJ3llaK3cMYGAx8LuEpsn8/edit?usp=sharing", sheet="Certifications") %>%
  vitae::detailed_entries(what = Organization,
                          when = Year,
                          where = Certification, 
                          with = Details)

```

## Publications

```{r}
gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1gEblFCo3xv83kw7G_JFSi5Cy9sKZCCHPBdCrUJxLvI4/edit?usp=sharing", sheet="Publications") %>%
  filter(category == "peer") %>%
  select(-category) %>%
  RefManageR::as.BibEntry() %>%
  RefManageR::WriteBib("peerreviewed.bib", biblatex=T)


vitae::bibliography_entries("peerreviewed.bib") %>%
  arrange(desc(issued))
```
